### ISSUE TITLE
Component refresh exceptions

### ISSUE THREAD

**Issue by wu-clan** [fastapi-practices/fastapi_best_architecture_ui_arco#12]
There seems to be a problem with the routing subscription mode, where components are not automatically updated when switching pages, but are rendered only after refreshing the interface

**Comment by downdawn** [comment]
Do you need to cache components?
[https://cn.vuejs.org/guide/built-ins/keep-alive.html](https://cn.vuejs.org/guide/built-ins/keep-alive.html)

**Comment by wu-clan** [comment]
Should not be directly related to this, not sure where the problem

My description is not clear enough, after the #11 merge, please pull the code and try to switch pages, the problem will appear

**Comment by downdawn** [comment]
Preliminary positioning points to the page-layout component. Removing the transition allows for normal switching.

It is possible that an issue related to custom menu routing is causing this, but the root cause has not been identified yet.

**Comment by wu-clan** [comment]
Yes, the problem is closely related to vue-router, which is not working as expected in some places because of the use of custom routes

Menu generation needs to be revamped

**Comment by wu-clan** [comment]
Solved, the main reason was that the vue-router component needed a unique key

Doesn't seem to be the reason for custom routes, but routers are more applicable now
