### ISSUE TITLE
build exception

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture_ui_arco#37]
v-model === v-model:model-value

only one can be kept：v-model

![image](https://github.com/fastapi-practices/fastapi_best_architecture_ui/assets/41266749/6b5670a3-943e-4202-a53b-0c1eb5c9ad29)

**Comment by wu-clan** [comment]
I'll try that later, since the form binds to an integer type, but the button needs to be of boolean type
