### ISSUE TITLE
Table columns watch

### ISSUE THREAD

**Issue by wu-clan** [fastapi-practices/fastapi_best_architecture_ui_arco#38]
Hi, @downdawn 

Based on the initial use: table's columns use cloneColumns, but shouldn't it use showColumns?

**Comment by downdawn** [comment]
watch can be deleted.
The complete code example is to have the column set this functionality.

![image](https://github.com/fastapi-practices/fastapi_best_architecture_ui/assets/41266749/5824b242-2781-4991-8ef9-fce2a76e6eda)

**Comment by wu-clan** [comment]
OK.
