### ISSUE TITLE
Hello, are the current ui version api and backend router unified?

### ISSUE THREAD

**Issue by georgeJzzz** [fastapi-practices/fastapi_best_architecture_ui_arco#52]
Hello, are the current ui version api and backend router unified?

Can the latest version be released later?

![a593a89f4e2823df9ccd343498a4390](https://github.com/fastapi-practices/fastapi_best_architecture_ui/assets/42543889/b3f8a63f-9fae-4c33-bd55-a62ce9d298b9)

**Comment by wu-clan** [comment]
Hello, our backend API has been redefined not long ago, and the front end has not been updated yet. I will synchronize it later today.

**Comment by georgeJzzz** [comment]
thanks
