### ISSUE TITLE
Error message alert exception

### ISSUE THREAD

**Issue by wu-clan** [fastapi-practices/fastapi_best_architecture_ui_arco#8]
Error message prompts sometimes display content other than that returned by the backend

and can also cause unexpected cross-domain errors

**Comment by downdawn** [comment]
Do you have a screenshot or can you provide the steps to reproduce the issue?

**Comment by wu-clan** [comment]
For example, the latest login interface, if the captcha is wrong or the captcha rate is limited

**Comment by wu-clan** [comment]
Ideally, the exception should be triggered by the request interceptor, but it does not seem to be

**Comment by wu-clan** [comment]
For example, the latest login interface, if the captcha is wrong or the captcha rate is limited

Ideally, all request exception information should be obtained by the request interceptor, but this is not the case
